import { jsPDF } from 'jspdf';

export function generateSimpleElectionResultsPDF(election, results) {
  // Validate inputs
  if (!election || !results || !Array.isArray(results)) {
    throw new Error('Invalid election or results data provided');
  }
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Colors
  const primaryColor = [102, 126, 234]; // #667eea
  const secondaryColor = [118, 75, 162]; // #764ba2
  const textColor = [45, 55, 72]; // #2d3748
  const lightGray = [248, 249, 250]; // #f8f9fa
  
  // ===== TITLE PAGE =====
  
  // Background gradient effect (simulated with rectangles)
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');
  
  // Add some pattern effect
  doc.setFillColor(255, 255, 255);
  doc.setGState(new doc.GState({opacity: 0.1}));
  for (let i = 0; i < 20; i++) {
    doc.circle(Math.random() * pageWidth, Math.random() * pageHeight, 2, 'F');
  }
  doc.setGState(new doc.GState({opacity: 1}));
  
  // Main logo and title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(48);
  doc.setFont('helvetica', 'bold');
  doc.text('🗳️', pageWidth / 2, 80, { align: 'center' });
  
  doc.setFontSize(32);
  doc.text('eVoting System', pageWidth / 2, 110, { align: 'center' });
  
  // Election title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'normal');
  doc.text('Official Results Report', pageWidth / 2, 140, { align: 'center' });
  
  // Election name in a box
  doc.setFillColor(255, 255, 255);
  doc.setGState(new doc.GState({opacity: 0.9}));
  doc.rect(30, 160, pageWidth - 60, 40, 'F');
  doc.setGState(new doc.GState({opacity: 1}));
  
  doc.setTextColor(...textColor);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(election.title, pageWidth / 2, 185, { align: 'center' });
  
  // Election details
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  
  const startDate = new Date(election.startTime).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
  
  const endDate = new Date(election.endTime).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
  
  doc.text(`Election Period: ${startDate} - ${endDate}`, pageWidth / 2, 230, { align: 'center' });
  doc.text(`Status: ${election.status.toUpperCase()}`, pageWidth / 2, 250, { align: 'center' });
  
  // Footer on title page
  doc.setFontSize(12);
  doc.text('This document contains official election results', pageWidth / 2, pageHeight - 30, { align: 'center' });
  doc.text('Generated by eVoting System', pageWidth / 2, pageHeight - 15, { align: 'center' });
  
  // ===== RESULTS PAGE =====
  doc.addPage();
  
  let yPosition = 20;
  
  // Results page header
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 30, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('📊 ELECTION RESULTS', pageWidth / 2, 20, { align: 'center' });
  
  yPosition = 50;
  
  // Total Votes
  const totalVotes = results.reduce((sum, result) => sum + (result.count || 0), 0);
  
  doc.setFillColor(...lightGray);
  doc.rect(20, yPosition - 5, pageWidth - 40, 25, 'F');
  
  doc.setTextColor(...textColor);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(`${totalVotes}`, pageWidth / 2, yPosition + 5, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Total Votes Cast', pageWidth / 2, yPosition + 15, { align: 'center' });
  
  yPosition += 40;
  
  // Results Table Header
  doc.setFillColor(...primaryColor);
  doc.rect(20, yPosition - 5, pageWidth - 40, 15, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  
  const colWidths = [20, 80, 30, 30, 40];
  const headers = ['Rank', 'Candidate', 'Votes', '%', 'Progress'];
  let xPos = 20;
  
  headers.forEach((header, index) => {
    doc.text(header, xPos + colWidths[index] / 2, yPosition + 3, { align: 'center' });
    xPos += colWidths[index];
  });
  
  yPosition += 20;
  
  // Results Table Rows
  doc.setTextColor(...textColor);
  doc.setFont('helvetica', 'normal');
  
  results.forEach((result, index) => {
    // Validate result data
    if (!result || typeof result.candidate !== 'string' || typeof result.count !== 'number') {
      console.warn(`Invalid result data at index ${index}:`, result);
      return;
    }
    
    // Alternate row colors
    if (index % 2 === 0) {
      doc.setFillColor(248, 249, 250);
      doc.rect(20, yPosition - 5, pageWidth - 40, 15, 'F');
    }
    
    xPos = 20;
    
    // Rank
    doc.setFont('helvetica', 'bold');
    doc.text(`${index + 1}`, xPos + colWidths[0] / 2, yPosition + 3, { align: 'center' });
    xPos += colWidths[0];
    
    // Candidate name
    doc.setFont('helvetica', 'normal');
    const candidateName = result.candidate.length > 20 ? 
      result.candidate.substring(0, 17) + '...' : result.candidate;
    doc.text(candidateName, xPos + 5, yPosition + 3);
    xPos += colWidths[1];
    
    // Vote count
    doc.setFont('helvetica', 'bold');
    doc.text(`${result.count}`, xPos + colWidths[2] / 2, yPosition + 3, { align: 'center' });
    xPos += colWidths[2];
    
    // Percentage
    const percentage = totalVotes > 0 ? ((result.count / totalVotes) * 100).toFixed(1) : 0;
    doc.text(`${percentage}%`, xPos + colWidths[3] / 2, yPosition + 3, { align: 'center' });
    xPos += colWidths[3];
    
    // Progress bar
    const progressWidth = totalVotes > 0 ? (result.count / totalVotes) * 35 : 0;
    doc.setFillColor(...primaryColor);
    doc.rect(xPos + 2, yPosition - 1, progressWidth, 7, 'F');
    doc.setFillColor(226, 232, 240);
    doc.rect(xPos + 2, yPosition - 1, 35, 7, 'S');
    
    yPosition += 15;
    
    // Add page break if needed
    if (yPosition > pageHeight - 50) {
      doc.addPage();
      yPosition = 20;
    }
  });
  
  // Footer
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
  
  doc.setTextColor(160, 174, 192);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated on: ${currentDate}`, pageWidth / 2, pageHeight - 20, { align: 'center' });
  doc.text('This is an official document generated by the eVoting System', pageWidth / 2, pageHeight - 10, { align: 'center' });
  
  return doc.output('arraybuffer');
}
